### ISSUE TITLE
Airgapped Support?

### ISSUE THREAD

**Issue by GideonStowell** [k3s-io/k3s-ansible#108]
[Question]
I am wanting to test this out in a airgapped environment, but am having a difficult time. I have a private registry stood up that has all the k3s related images it needs to start using the regular k3s install process. And I have successfully installed k3s numerous times with this same registry. So I feel confident the issue will not be in this portion of the system. 
I have been looking at the `k3s-ansible/roles/download/tasks/main.yml` file and I was hoping I could easily replace the provided urls with my private registry urls, but from some attempts and online research I beginning to question if you can download docker images through http.

Does anyone here know a better way to download the docker images in this manner? Thanks

**Comment by pwntr** [comment]
HI! I had the same goal, and achieved it relatively easily by downloading the pre-packaged k3s airgap images .tar archive to a local webserver, and pointing the URL in the file you referenced to that address. Plus some added tasks to transfer the archive to the right destination. See PR #114 for a reference and detailed instructions.

The URL in the role/task does not point to a container registry, but indeed to a plain web server and dir. For the registry approach and the manual approach (automated here via Ansible in my PR). [This doc](https://rancher.com/docs/k3s/latest/en/installation/airgap/) sums up the steps.

Referencing a private registry directly should also be possible, but require other steps outlined in the k3s doc above and then translated to Ansible tasks, of course.

Cheers

**Comment by GideonStowell** [comment]
You're a good man! I forgot I had created this issue - I ended up doing a similar thing to what you did in the PR. 

In the process I did also make a take that installed a pre-made registries.yaml file in /etc/rancher/k3s and was able to do an airgapped install this way too )as long as the registry actually has the k3s images). But like I said , we decided that installing the tarball is an easier solution 

Thanks for looking at this!

**Comment by GidStowell** [comment]
@pwntr I've been integrating this into the additional ansible stuff that we have and thought of a question I can't seem to find the answer to. I thought I'd give you a try: What is the "boot order" (for lack of a better term) when it comes to the k3s images? For example, if I have the tarball installed properly AND the registries.yaml installed, will it first look for the tarball and then at the rergistries.yaml, and then the internet? I'm curious what the precedence order is.

**Comment by pwntr** [comment]
@GidStowell that is an interesting question. Without diving into the K3s code itself, my **hypothesis** would be the following order for image pulls:

1. check tarball / local node image cache
2. private registry
3. internet

Why? The tarball, in my understanding, directly populates the node's **local** image cache with the required system images needed by K3s. If the images are not present locally in that cache, K3s will try to pull them from a private registry, if defined in the `registries.yaml` (and would there also follow the order of preference configured if multiple registries are configured there). Only if the requested image ID is _not_ already present in either the local cache or the private registry / registries, a pull from docker hub / internet would be attempted (if not disallowed or proxied by entries in the `registries.yaml` manually).

At the end of the day, the goal of an image pull should always be to satisfy the presence of an image ID on a given target node's local cache. If it's already there, by means of a previous tarball distribution or otherwise, other ways don't need to be triggered. _"Hey node 42, you got image ID 5gey47637df already in your cache? Yeah? Cool, carry on!"_.

As said, this is just my hypothesis. I haven't cross-checked this with docs or a code review. But it would make sense to me in my current understanding if K3s and other Kubernetes distributions would handle it in this or a very similar way.

**Comment by GidStowell** [comment]
That's what made sense to me - all I needed was to hear someone else say it too. Thanks for the help and attention - I'll close this issue.

**Comment by dereknola** [comment]
I am reopening this issue to track this feature. This repo now utilized the https://get.k3s.io script for installation, and airgap support need to be reworked.
